[customizations.installer.kickstart]
contents = """
lang en_US.UTF-8
keyboard us

%post
bootc switch --mutate-in-place --transport registry ghcr.io/abirkel/vespera:latest
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users"
]

disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
